kind: Service
apiVersion: v1
metadata:
  name: my-flask-app-service
spec:
  type: LoadBalancer
  selector:
    app: my-flask-app
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 33333   
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app-deployment
  labels:
    app: my-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 5000
